import { useEffect } from "react";
const EOSSPolicy = () => {
   useEffect(() => {
      window.scrollTo(0, 0);
    }, []);
  return (
    <section className="max-w-7xl mx-auto mt-8 px-5 py-10">
      {/* Breadcrumb */}

      <p className="text-xs text-gray-500 mb-4">
        <a href="/">Home/ </a>
        <span>EOSS Terms & Conditions Policy</span>
      </p>

      <h1 className="text-xl font-bold text-gray-800  ">
        EOSS Terms & Conditions
      </h1>

      <h2 className="text-sm text-gray-800 mb-4">ONLINE</h2>

      <p className="text-gray-700 text-sm mb-4 leading-8">
        The terms and conditions (hereinafter referred to as the “EOSS T&C”)
        mentioned below shall be applicable to all purchase(s) made from the
        SALE section during the EOSS (END OF SEASON SALE) period on
        www.faridagupta.com (hereinafter referred to as the “FG Website”)
        conducted by Farida Gupta Retail Private Limited (‘FG’). It is clarified
        that the EOSS period shall be from 7th January 2023 (12 AM IST) till
        15th February 2023 (both days inclusive) unless modified, revoked or
        extended by FG. Any such revocation or extension may be made by FG
        without any prior notice and/or incurring any liability.
      </p>

      <p className="mb-8 text-sm leading-8 text-gray-700">
        The EOSS T&C shall also govern the offer(s) being provided on the
        Website during the EOSS Period. The EOSS T&C are to be read in
        conjunction with the Terms & Conditions (hereinafter referred to as the
        “T&C”) mentioned on the FG website. It is clarified that any term not
        defined specifically in the EOSS T&C shall be given the meaning ascribed
        in the T&C available on the FG Website. In the event of any
        contradiction between the T&C and the EOSS T&C, the EOSS T&C shall
        supervene over the T&C for fresh purchase(s) made from the SALE section
        during the EOSS Period, except to the extent specified herein
      </p>

      <h2 className="text-lg text-gray-800 font-semibold mb-4">Exhibition</h2>

      <p className="mb-2 leading-8 text-sm text-gray-700">
        The Exhibition EOSS T&C are to be read in conjunction with the Terms &
        Conditions (hereinafter referred to as the “T&C”) mentioned on the FG
        website. It is clarified that any term not defined specifically in the
        EOSS T&C shall be given the meaning ascribed in the T&C available on the
        FG Website. In the event of any contradiction between the T&C and the
        Exhibition EOSS T&C, the Exhibition EOSS T&C shall supervene over the
        T&C for fresh purchase(s) made from the SALE section during the EOSS
        Period, except to the extent specified herein.
      </p>
      <p className="mb-8 leading-8 text-sm text-gray-700">
        The terms and conditions (hereinafter referred to as the “Exhibition
        EOSS T&C”) mentioned below shall be applicable to all purchase(s) made
        from the SALE section during the EOSS (END OF SEASON SALE) period at the
        Exhibition (hereinafter referred to as the “Exhibition/FG Exhibition”)
        conducted by Farida Gupta Retail Pvt. Ltd (hereinafter referred to as
        “FG/FGRPL”). It is clarified that the EOSS period shall be from 7th
        January 2023 (12 AM IST) till 15th February 2023 (both days inclusive)
        unless modified, revoked or extended by FG. Any such modification,
        revocation or extension may be made by FG without any prior notice
        and/or incurring any liability.
      </p>

      <h2 className="text-lg text-gray-800 font-semibold mb-4">
        General Terms & Conditions:
      </h2>

      <ul className="list-disc pl-8 mb-4 space-y-2 leading-8 text-sm text-gray-700">
        <li>
          This document is an electronic record in terms of Information
          Technology Act, 2000, and the Rules thereunder, as applicable. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </li>
        <li>
          The offer(s) shall be applicable to the selected products displayed on
          the website under the ‘SALE’ tab during the EOSS period.
        </li>
        <li>
          FG reserves the right, at its sole discretion, to change, modify or
          remove the offers at any given point of time, without any prior
          notice.
        </li>
        <li>
          Purchases/attempt to purchase made by a customer (also referred to as
          “you/your”), during the EOSS Period, shall be deemed as consent of the
          customer to the EOSS T&C.
        </li>
        <li>
          Any fraudulent behaviour may result in cancellation of any order
          and/or inability to access the FG website. FG has the right, in its
          sole discretion, to disqualify or prohibit from participating in the
          promotion any individual who FG believes has engaged, has attempted to
          or intends to attempt to engage, in conduct that annoys, abuses,
          threatens, or harasses any other participant or any representative of
          FG. The use of agents or automated devices, programs, or methods to
          participate is prohibited, and FG has the right, in its sole
          discretion, to disqualify any participant that it believes may have
          participated using such an agent or automated device, program, or
          method.
        </li>
        <li>
          The Company reserves the right to disqualify/blacklist any
          participant(s)/customer(s) that attempts to tamper/misuse or tampers
          /misuses or breaches the EOSS T&C or the other T&C mentioned on the FG
          Website, in any manner.
        </li>
        <li>
          No returns/exchanges will be entertained against international orders
          as per regular practice. Standard Terms & Conditions pertaining to
          returns/exchanges will be applicable in case of domestic orders.
        </li>
        <li>
          All disputes concerning the sale and purchase made during the EOSS
          Period shall be governed by the laws of India and shall be subject to
          the jurisdiction of the Delhi courts.
        </li>
      </ul>
    </section>
  );
};

export default EOSSPolicy;
